services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - "./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/project/public"
    depends_on:
      - app
  app:
    container_name: app
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      - "./:/var/www/project"
